name: test-inputs

on: 
  push:

jobs:
  test-context:
    runs-on: ubuntu-latest

    steps:
      - name: Using context variables
        run: |
          echo "This workflow was triggered by ${{ github.actor }}"
          echo "The repository name is ${{ github.repository }}"

      - name: Print all variables in GitHub
        run: echo '${{ toJson(github) }}'
