name: test-inputs
on: push
jobs:
  test-context:
    runs-on: ubuntu-latest
    steps:
      - name: using context variables
        run: |
          echo "this workflow triggered by ${{ github.actor}}
          echo "the repo name is ${{  github.repository}}
      - name: print all variables in github
        run: echo "${{ toJson(github) }}"
